branch-defaults:
  aws:
    environment: Storytellingandcognition-env
  main:
    environment: Storytellingandcognition-env
environment-defaults:
  Storytellingandcognition-env:
    branch: aws
    repository: origin
global:
  application_name: Storytelling-and-Cognition
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
